// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using test_dotnet_app.DbStore;

#nullable disable

namespace test_dotnet_app.Migrations
{
    [DbContext(typeof(EntityDbContext))]
    [Migration("20240823171724_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("test_dotnet_app.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DepartmentId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 8, 23, 22, 47, 24, 797, DateTimeKind.Local).AddTicks(1903),
                            Name = "Sales",
                            UpdatedAt = new DateTime(2024, 8, 23, 22, 47, 24, 797, DateTimeKind.Local).AddTicks(1913)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 8, 23, 22, 47, 24, 797, DateTimeKind.Local).AddTicks(1916),
                            Name = "Marketing",
                            UpdatedAt = new DateTime(2024, 8, 23, 22, 47, 24, 797, DateTimeKind.Local).AddTicks(1916)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 8, 23, 22, 47, 24, 797, DateTimeKind.Local).AddTicks(1917),
                            Name = "Engineering",
                            UpdatedAt = new DateTime(2024, 8, 23, 22, 47, 24, 797, DateTimeKind.Local).AddTicks(1918)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 8, 23, 22, 47, 24, 797, DateTimeKind.Local).AddTicks(1919),
                            Name = "Finance",
                            UpdatedAt = new DateTime(2024, 8, 23, 22, 47, 24, 797, DateTimeKind.Local).AddTicks(1919)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 8, 23, 22, 47, 24, 797, DateTimeKind.Local).AddTicks(1920),
                            Name = "HR",
                            UpdatedAt = new DateTime(2024, 8, 23, 22, 47, 24, 797, DateTimeKind.Local).AddTicks(1920)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 8, 23, 22, 47, 24, 797, DateTimeKind.Local).AddTicks(1921),
                            Name = "IT",
                            UpdatedAt = new DateTime(2024, 8, 23, 22, 47, 24, 797, DateTimeKind.Local).AddTicks(1921)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 8, 23, 22, 47, 24, 797, DateTimeKind.Local).AddTicks(1922),
                            Name = "Operations",
                            UpdatedAt = new DateTime(2024, 8, 23, 22, 47, 24, 797, DateTimeKind.Local).AddTicks(1922)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2024, 8, 23, 22, 47, 24, 797, DateTimeKind.Local).AddTicks(1923),
                            Name = "Product Management",
                            UpdatedAt = new DateTime(2024, 8, 23, 22, 47, 24, 797, DateTimeKind.Local).AddTicks(1924)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2024, 8, 23, 22, 47, 24, 797, DateTimeKind.Local).AddTicks(1924),
                            Name = "Quality Assurance",
                            UpdatedAt = new DateTime(2024, 8, 23, 22, 47, 24, 797, DateTimeKind.Local).AddTicks(1925)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2024, 8, 23, 22, 47, 24, 797, DateTimeKind.Local).AddTicks(1926),
                            Name = "R&D",
                            UpdatedAt = new DateTime(2024, 8, 23, 22, 47, 24, 797, DateTimeKind.Local).AddTicks(1926)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2024, 8, 23, 22, 47, 24, 797, DateTimeKind.Local).AddTicks(1930),
                            Name = "Sales Support",
                            UpdatedAt = new DateTime(2024, 8, 23, 22, 47, 24, 797, DateTimeKind.Local).AddTicks(1930)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2024, 8, 23, 22, 47, 24, 797, DateTimeKind.Local).AddTicks(1931),
                            Name = "Training & Development",
                            UpdatedAt = new DateTime(2024, 8, 23, 22, 47, 24, 797, DateTimeKind.Local).AddTicks(1932)
                        });
                });

            modelBuilder.Entity("test_dotnet_app.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EmployeeId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 8, 23, 22, 47, 24, 797, DateTimeKind.Local).AddTicks(2346),
                            DepartmentId = 1,
                            FirstName = "John",
                            LastName = "Doe",
                            UpdatedAt = new DateTime(2024, 8, 23, 22, 47, 24, 797, DateTimeKind.Local).AddTicks(2348)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 8, 23, 22, 47, 24, 797, DateTimeKind.Local).AddTicks(2351),
                            DepartmentId = 2,
                            FirstName = "Jane",
                            LastName = "Smith",
                            UpdatedAt = new DateTime(2024, 8, 23, 22, 47, 24, 797, DateTimeKind.Local).AddTicks(2351)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 8, 23, 22, 47, 24, 797, DateTimeKind.Local).AddTicks(2352),
                            DepartmentId = 3,
                            FirstName = "Mike",
                            LastName = "Johnson",
                            UpdatedAt = new DateTime(2024, 8, 23, 22, 47, 24, 797, DateTimeKind.Local).AddTicks(2352)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 8, 23, 22, 47, 24, 797, DateTimeKind.Local).AddTicks(2353),
                            DepartmentId = 4,
                            FirstName = "Sarah",
                            LastName = "Wilson",
                            UpdatedAt = new DateTime(2024, 8, 23, 22, 47, 24, 797, DateTimeKind.Local).AddTicks(2354)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 8, 23, 22, 47, 24, 797, DateTimeKind.Local).AddTicks(2390),
                            DepartmentId = 5,
                            FirstName = "Michael",
                            LastName = "Davis",
                            UpdatedAt = new DateTime(2024, 8, 23, 22, 47, 24, 797, DateTimeKind.Local).AddTicks(2391)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 8, 23, 22, 47, 24, 797, DateTimeKind.Local).AddTicks(2392),
                            DepartmentId = 6,
                            FirstName = "Emily",
                            LastName = "Thompson",
                            UpdatedAt = new DateTime(2024, 8, 23, 22, 47, 24, 797, DateTimeKind.Local).AddTicks(2392)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 8, 23, 22, 47, 24, 797, DateTimeKind.Local).AddTicks(2393),
                            DepartmentId = 7,
                            FirstName = "Daniel",
                            LastName = "Brown",
                            UpdatedAt = new DateTime(2024, 8, 23, 22, 47, 24, 797, DateTimeKind.Local).AddTicks(2393)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2024, 8, 23, 22, 47, 24, 797, DateTimeKind.Local).AddTicks(2394),
                            DepartmentId = 8,
                            FirstName = "Sarah",
                            LastName = "Evans",
                            UpdatedAt = new DateTime(2024, 8, 23, 22, 47, 24, 797, DateTimeKind.Local).AddTicks(2394)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2024, 8, 23, 22, 47, 24, 797, DateTimeKind.Local).AddTicks(2395),
                            DepartmentId = 9,
                            FirstName = "Max",
                            LastName = "Evans",
                            UpdatedAt = new DateTime(2024, 8, 23, 22, 47, 24, 797, DateTimeKind.Local).AddTicks(2396)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2024, 8, 23, 22, 47, 24, 797, DateTimeKind.Local).AddTicks(2396),
                            DepartmentId = 10,
                            FirstName = "Emily",
                            LastName = "Evans",
                            UpdatedAt = new DateTime(2024, 8, 23, 22, 47, 24, 797, DateTimeKind.Local).AddTicks(2397)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2024, 8, 23, 22, 47, 24, 797, DateTimeKind.Local).AddTicks(2398),
                            DepartmentId = 11,
                            FirstName = "Micky",
                            LastName = "Evans",
                            UpdatedAt = new DateTime(2024, 8, 23, 22, 47, 24, 797, DateTimeKind.Local).AddTicks(2398)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2024, 8, 23, 22, 47, 24, 797, DateTimeKind.Local).AddTicks(2399),
                            DepartmentId = 12,
                            FirstName = "Kyle",
                            LastName = "Evans",
                            UpdatedAt = new DateTime(2024, 8, 23, 22, 47, 24, 797, DateTimeKind.Local).AddTicks(2399)
                        });
                });

            modelBuilder.Entity("test_dotnet_app.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ResetPasswordToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResetPasswordTokenExpiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("test_dotnet_app.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("test_dotnet_app.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("test_dotnet_app.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("test_dotnet_app.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("test_dotnet_app.Entities.Employee", b =>
                {
                    b.HasOne("test_dotnet_app.Entities.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("test_dotnet_app.Entities.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
